Initialize TestGuru
ertiyuo/thinknetica-rails pull request #1
Opened 2022-02-22 15:05 UTC by ertiyuo

2022-02-24 07:46 UTC, VidgarVii requested changes

2022-02-24 07:46 UTC, VidgarVii commented on README.md
> +- Testees
как-то мало получилось сущностей )))

список сущностей приложения обычно выводится из сценария использования приложения

сценарий использования приложения примерно такой:
- Пользователь заходит на сайт
- он выбирает Тест
- Тест может принадлежать к одной из Категорий
- Тест состоит из Вопросов
- на каждый Вопрос есть несколько Ответов
- Пользователь выбирает один или несколько Ответов, чтобы ответить на каждый из Вопросов
- Результат тестирования сохраняется

2022-02-24 07:46 UTC, VidgarVii commented on README.md
> +- Testees
Creators и Testees это всё пользователи системы

2022-02-24 07:46 UTC, VidgarVii commented on app/controllers/about_controller.rb
> +class AboutController < ApplicationController
`html` файлы целиком статические
их будет оптимальнее отдать вообще в обход рельсового приложения (так будет работать быстрее, да и рельсам с этими файлами делать то нечего)
для этого их достаточно поместить в директорию `public`

роуты при этом не нужны и контроллеры тоже
(путь к файлу внутри директории `public` должен соответствовать пути, по которому этот файл должен быть доступен)

2022-02-24 07:46 UTC, VidgarVii commented on config/initializers/locale.rb
> +I18n.default_locale = :ru
1 по ДЗ достаточно указать локаль по умолчанию
2 Все общие настройки приложения хранятся в config/application.rb и так же настраивается обращаясь к config

2022-02-24 07:46 UTC, VidgarVii commented on config/initializers/version.rb
> +    VERSION = "0.1"
по соглашению должно быть 3 цифры.
сразу про константы следующий момент:
"мутабельные" объекты (строки, хэши, массивы) рекомендуется `freeze`-ить, чтобы они были неизменяемыми
в противном случае константу, ссылающуюся на "мутабельный" объект,  можно изменить: `VERSION << '3.14..'`

2022-02-24 07:46 UTC, VidgarVii commented on app/views/about/author.html.erb
> +<p>Github: <a href="https://github.com/ertiyuo">ertiyuo</a></p>
ссылки на сторонние ресурсы правильно открывать в новой вкладке и хорошо бы добавить опцию rel=nofollow rel=noopener. Так клиента сохраним и поискового робота дальше не пустим

2022-02-24 07:46 UTC, VidgarVii commented on app/views/about/author.html.erb
> +<p>Github: <a href="https://github.com/ertiyuo">ertiyuo</a></p>
в конце файла надо отставлять 1 пустую строчку. Это указатель на конец файла. Сейчас система думает, что происходит обрыв файла. Даже гитхаб ругается. No new lina at end of file

2022-03-02 16:21 UTC, VidgarVii commented on public/about/author.html
> +<h1>Test Guru</h1>
файлы из `public` отдаются минуя контроллеры "как есть", т.е. без лэйаута
это означает, что здесь должен быть полноценная `html` страница, которая открывается тегом `<!DOCTYPE html>` и содержит теги `<html>`, `<head>`, `<body>` и т.д.

2022-03-02 16:21 UTC, VidgarVii commented on public/about/index.html
> +﻿<h1>Test Guru</h1>
тоже самое

2022-03-02 18:47 UTC, merged

2022-03-03 06:09 UTC, ertiyuo commented on app/controllers/about_controller.rb
> +class AboutController < ApplicationController
У меня есть вопрос - как в таком случае менять локаль для всего приложения сразу? Переписывать каждый раз страницы со статической информацией?